### PR TITLE
Update Uncurried.py

### PR DESCRIPTION
**Pull request by mikesol**
It turned out that the bug in `purescript-simple-json` came from an error in this file. When I wrote it to look like the JS implementation the error went away, so perhaps we can use this?

### CODE REVIEW

**Comment by thautwarm** [comment]
Does this work?

**Comment by thautwarm** [comment]
If so I feel like to merge.

**Comment by mikesol** [comment]
Yes, it works. Will merge :)

**Comment by thautwarm** [comment]
Good, seems that boilerplates are not a problem to you :)

**Pull request merged**
